"""empty message

Revision ID: 4783fa306d1a
Revises: 3a31d6fac939
Create Date: 2016-10-19 21:16:08.775656

"""

# revision identifiers, used by Alembic.
revision = '4783fa306d1a'
down_revision = '3a31d6fac939'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('TaskName', sa.String(), nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_tasks'),
    sqlite_autoincrement=True
    )
    op.create_index('ix_tasks_Description', 'tasks', ['Description'], unique=False)
    op.create_index('ix_tasks_TaskName', 'tasks', ['TaskName'], unique=False)
    #op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    op.drop_index('ix_tasks_TaskName', table_name='tasks')
    op.drop_index('ix_tasks_Description', table_name='tasks')
    op.drop_table('tasks')
    ### end Alembic commands ###
