"""empty message

Revision ID: 4d0e1a73d197
Revises: 4783fa306d1a
Create Date: 2016-11-02 19:36:56.922683

"""

# revision identifiers, used by Alembic.
revision = '4d0e1a73d197'
down_revision = '4783fa306d1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sqlite_sequence')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sqlite_sequence',
    sa.Column('name', sa.NullType(), nullable=True),
    sa.Column('seq', sa.NullType(), nullable=True)
    )
    ### end Alembic commands ###
